Models/GetGrades.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2.Models
{
    public class GetGrades
    {
        public int grade { get; set;}
    }
}

Controllers/SubfolderController.cs
using Microsoft.AspNetCore.Mvc;
using Mission2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission2.Controllers
{
    public class SubfolderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GetGrades model)
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link href="bootstrap-5.1.3-dist/bootstrap-5.1.3-dist/css/bootstrap.css" rel="stylesheet" />
    <link href="lib/css/Default.css" rel="stylesheet" />
    <title>@ViewData["Title"]</title>
    <!-- add icon link -->
    <link rel="icon" href="Professional Square photo.jpg"
          type="image/x-icon">
</head>
<body>

    <nav>
        <a asp-controller="Subfolder" asp-action="GradeCalculator">Get Grades</a>
        <a asp-controller="Subfolder" asp-action="Index">Home</a>
    </nav>
    <div>
        @RenderBody()
    </div>


    <script src="lib/jquery/Default.js"></script>
    <script src="bootstrap-5.1.3-dist/bootstrap-5.1.3-dist/js/bootstrap.js"></script>

</body>
</html>

Views/Subfolder/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "View Grades";

}

<form method="post">
    <label>Assignments: </label> <input type="number" min="0" max="100" id="Assignments" asp-for="Assignments" /> <br />
    <label>Group Project: </label> <input type="number" min="0" max="100" id="Group Projects" asp-for="Group Projects" /> <br />            
    <label>Quizzes: </label> <input type="number" min="0" max="100" id="Quizzes" asp-for="Quizzes" /> <br />
    <label>Exams: </label> <input type="number" min="0" max="100" id="Exams" asp-for="Exams" /> <br />
    <label>INTEX: </label> <input type="number" min="0" max="100" id="INTEX" asp-for="INTEX" /> <br /><br />
    <input type="submit" id="GetGrades" asp-for="GetGrades" value="Get your grades!" />
</form>

Views/Subfolder/Index.cshtml
@*
For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{      ViewData["Title"] = "IS 413 is the Best";
}


<h1>James Peterson</h1>
<br /><br /><br />
<img src="WhatIlove.png.jpg" />
<br /><br /><br />
<p>
    I would love to learn from this class what I need to do to be able to be a better candidate for jobs. I would like to understand
    how to program in ASP.net so that I am desired in my career. I would like to become good friends with Professor Hilton, I would like to
    learn what it is that he does to make everyone happy with him. It would also be nice to get a good grade in the end, but as long as I
    learn the material, that is honestly the most important part.
</p><br />

<H2>Top 3 jobs I am interested in pursuing for a career:</H2><br />
<ol>
    <li>Data Analyst</li>
    <li>Developer</li>
    <li>Information Security guy</li>
</ol>

<h3>Grade Calculator:</h3>
<p>Please insert the percentage you received in each category in the following format, 95% as 95 23% as 23 etc.</p> <br />